title:              Product. Design. Tech.
email:              sheia.official@gmail.com
description:        Think About Things Differently
author:             Sheia Anandaraj
baseurl:            ""
url:                "https://sheia.github.io"

# Social Profiles
twitter_username:   
github_username:    sheia
facebook_username:  
instagram_username:  
linkedin_username:	sheia

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-172905762-1 # out your google-analytics code

# Build settings
theme: startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
 
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
#remote_theme : StartBootstrap/startbootstrap-clean-blog-jekyll
