title:              Product. Design. Technology
email:              sheia.official@gmail.com
description:        Think About Things Differently
author:             Sheia Anandaraj
baseurl:            ""
url:                "https://sheia.github.io"

# Social Profiles
twitter_username:   
github_username:    sheia
facebook_username:  
instagram_username:  
linkedin_username:	sheia

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
 

remote_theme : StartBootstrap/startbootstrap-clean-blog-jekyll
